version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npx next export
  post_build:
    commands:
      - aws s3 sync out/ s3://furuta-backet/ --delete
artifacts:
  files:
    - '**/*'
  base-directory: out
